Repository codeit-bootcamp-frontend/7-Sprint-Mission, pull requests merged in 2024-04, with the labels that each got.

#9 [김광호] Sprint1
  Privacy.html
  cssfile.css
  faq.html
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/instagram-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  items.html
  login.html
  mainpage.html
Labels: 매운맛🔥

#26 [이태진] Sprint 1
  sprint_mission1/image/footer_picture.png
  sprint_mission1/image/header_picture.png
  sprint_mission1/image/hot_item_picture.png
  sprint_mission1/image/ic_facebook.png
  sprint_mission1/image/ic_instagram.png
  sprint_mission1/image/ic_twitter.png
  sprint_mission1/image/ic_youtube.png
  sprint_mission1/image/panda_face.png
  sprint_mission1/image/panda_market_logo.png
  sprint_mission1/image/register_picture.png
  sprint_mission1/image/search_picture.png
  sprint_mission1/index.html
  sprint_mission1/style.css
Labels: 매운맛🔥

#31 [오조환] Sprint1
  footer-image.svg
  footer-logo.svg
  forder.svg
  green.svg
  head-image.svg
  index.html
  items.html
  logo.svg
  magnifier.svg
  style.css
Labels: 매운맛🔥

#19 [손권우] Sprint1
  faq.html
  fonts/ROKAF Sans Bold.otf
  fonts/ROKAF Sans Medium.otf
  fonts/ROKAF Slab Serif Bold.otf
  fonts/ROKAF Slab Serif Medium.otf
  image/Img_home_01.svg
  image/Img_home_02.svg
  image/Img_home_03.svg
  image/Img_home_bottom.png
  image/Img_home_top.svg
  image/ic_facebook.svg
  image/ic_instagram.svg
  image/ic_twitter.svg
  image/ic_youtube.svg
  image/logo.png
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#12 [신지원] Sprint1
  images/bottom.png
  images/facebook.svg
  images/favicon.ico
  images/img1.png
  images/img2.png
  images/img3.png
  images/insta.svg
  images/logo.svg
  images/navi.png
  images/twitter.svg
  images/youtube.svg
  index.html
  mission1.css
Labels: 매운맛🔥, 미완성🫠

#30 [황병선] Sprint1
  .DS_Store
  Img/Img_home_01.png
  Img/Img_home_02.png
  Img/Img_home_03.png
  Img/Img_home_bottom.png
  Img/Img_home_top.png
  Img/Property 1=Variant3.png
  Img/ic_facebook.png
  Img/ic_instagram.png
  Img/ic_twitter.png
  Img/ic_youtube.png
  index.html
  reset.css
  style.css
Labels: 순한맛🐑, 미완성🫠

#16 [송효정] Sprint1
  index.html
  src/css/reset.css
  src/css/style.css
  src/img/common/ic_facebook.svg
  src/img/common/ic_instagram.svg
  src/img/common/ic_twitter.svg
  src/img/common/ic_youtube.svg
  src/img/common/logo.png
  src/img/main/img_home_01.png
  src/img/main/img_home_02.png
  src/img/main/img_home_03.png
  src/img/main/img_home_bottom.png
  src/img/main/img_home_top.png
Labels: 매운맛🔥

#34 [김가영] Sprint1
  Group 19.png
  Img_home_01.png
  Img_home_02-1.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  mission_1.css
Labels: 미완성🫠

#18 [장아영] sprint 1
  .DS_Store
  판다마켓/.DS_Store
  판다마켓/Img_home_01.png
  판다마켓/Img_home_02-1.png
  판다마켓/Img_home_03.png
  판다마켓/Img_home_bottom.png
  판다마켓/Img_home_top.png
  판다마켓/Property 1=Typo.png
  판다마켓/Property 1=Variant3.png
  판다마켓/ic_X.png
  판다마켓/ic_facebook.png
  판다마켓/ic_instagram.png
  판다마켓/ic_instagram.svg
  판다마켓/ic_plus.png
  판다마켓/ic_profile.png
  판다마켓/ic_search.png
  판다마켓/ic_search_darker.png
  판다마켓/ic_sort.png
  판다마켓/ic_twitter.png
  판다마켓/ic_youtube.png
  판다마켓/pandamarket2.css
  판다마켓/pandamarket2.html
  판다마켓/status=Default (1).png
  판다마켓/status=Default.png
Labels: 매운맛🔥

#27 [정한주] Sprint 1
  panda1/Img_home_01.png
  panda1/Img_home_02.png
  panda1/Img_home_03.png
  panda1/Img_home_bottom.png
  panda1/Img_home_top.png
  panda1/btn_login.png
  panda1/fb.png
  panda1/index.html
  panda1/inst.png
  panda1/logo.png
  panda1/screenshot/mission1.png
  panda1/style.css
  panda1/twt.png
  panda1/yt.png
Labels: 매운맛🔥

#35 [김당찬] Sprint1
  css/main.css
  images/Img_home_01.png
  images/Img_home_01@2x.png
  images/Img_home_01@3x.png
  images/Img_home_02.png
  images/Img_home_02@2x.png
  images/Img_home_02@3x.png
  images/Img_home_03.png
  images/Img_home_03@2x.png
  images/Img_home_03@3x.png
  images/Img_home_bottom.png
  images/Img_home_bottom@2x.png
  images/Img_home_bottom@3x.png
  images/Img_home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  images/logo@2x.png
  images/logo@3x.png
  index.html
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
Labels: 매운맛🔥

#10 [최민경] Sprint1
  README.md
  html/faq.html
  html/items.html
  html/login.html
  html/privacy.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/header-logo.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  index.html
  style.css
Labels: 매운맛🔥

#21 [함다윤] sprint1
  .github/pull_request_template.md
  faq.html
  images/Group19.png
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  index.html
  items.html
  login.html
  privacy.html
  screencapture.png
  style.css
  판다_얼굴.png
Labels: 매운맛🔥

#14 [이윤재]Sprint7
  .github/pull_request_template.md
  faq.html
  index.html
  items.html
  login.html
  pictures/facebook.png
  pictures/hotitem.png
  pictures/instargram.png
  pictures/register.png
  pictures/search.png
  pictures/twitter.png
  pictures/youtube.png
  pictures/미션1완성사진.png
  pictures/판다 얼굴.png
  pictures/판다1.png
  pictures/판다2.png
  privacy.html
  style.css
Labels: 매운맛🔥

#23 [하유리] Sprint7
  .vscode/settings.json
  css/index.css
  css/login.css
  css/signup.css
  css/style.css
  faq.html
  font/ROKAF-Sans-Bold.woff
  font/ROKAF-Sans-Medium.woff
  image/Component 2.png
  image/Component 3.png
  image/btn_visibility_off_24px.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/image-logo.png
  image/img_home_01.png
  image/img_home_02.png
  image/img_home_03.png
  image/img_home_bottom.png
  image/img_home_top.png
  image/login-btn.png
  image/logo.png
  image/logo_panda.png
  image/logo_pandamarket.png
  image/shopping-btn.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
Labels: 매운맛🔥

#25 [김도용] Sprint1
  week1/image/Img_home_01.png
  week1/image/Img_home_02.png
  week1/image/Img_home_03.png
  week1/image/Img_home_bottom.png
  week1/image/Img_home_top.png
  week1/image/ic_facebook.png
  week1/image/ic_instagram.png
  week1/image/ic_twitter.png
  week1/image/ic_youtube.png
  week1/image/logo.png
  week1/index.html
  week1/style.css
Labels: 매운맛🔥

#24 [오성준] Sprint1
  faq.html
  images/Group 19-1.png
  images/Group 19-2.png
  images/Group 19.png
  images/Group 19@2x-1.png
  images/Group 19@2x-2.png
  images/Group 19@2x.png
  images/Group 19@3x-1.png
  images/Group 19@3x-2.png
  images/Group 19@3x.png
  images/Img_home_01.png
  images/Img_home_01@2x.png
  images/Img_home_01@3x.png
  images/Img_home_02.png
  images/Img_home_02@2x.png
  images/Img_home_02@3x.png
  images/Img_home_03.png
  images/Img_home_03@2x.png
  images/Img_home_03@3x.png
  images/Img_home_bottom.png
  images/Img_home_bottom@2x.png
  images/Img_home_bottom@3x.png
  images/Img_home_top.png
  images/Property 1=Typo.png
  images/Property 1=Typo@2x.png
  images/Property 1=Typo@3x.png
  images/Property 1=Variant3.png
  images/Property 1=Variant3@2x.png
  images/Property 1=Variant3@3x.png
  images/btn_visibility_off_24px.svg
  images/btn_visibility_on_24px-1.svg
  images/btn_visibility_on_24px-2.svg
  images/btn_visibility_on_24px.svg
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  images/logo@2x.png
  images/logo@3x.png
  images/판다 얼굴.png
  images/판다 얼굴@2x.png
  images/판다 얼굴@3x.png
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#22 [최예원] Sprint1
  .vscode/settings.json
  images/.DS_Store
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/Img_logo.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  index.html
  style.css
Labels: 매운맛🔥

#28 [강한솔] Sprint1
  Group 19.png
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  items.html
  login.html
  style.css
  판다 얼굴.png
Labels: 매운맛🔥

#5 [김예준]sprint 1
  bottom.png
  facebook.png
  image_home_01.png
  image_home_02.png
  image_home_03.png
  image_home_bottom.png
  image_home_top.png
  instar.png
  last.png
  login.png
  logo.png
  search.png
  sprin.css
  sprinter.html
  top.png
  twiter.png
  youtube.png
Labels: 매운맛🔥
