Repository codeit-bootcamp-frontend/7-Sprint-Mission, pull requests merged in 2024-07, with the labels that each got.

#227 [손권우] Sprint8
  public/faq.html
  public/index.html
  public/items.html
  public/login.html
  public/privacy.html
  public/signup.html
  src/components/modules/comment/comment.jsx
  src/components/modules/comment/comment.module.css
  src/components/pages/login/Login.jsx
  src/components/pages/login/Login.module.css
  src/components/ui/productdetail/productdetail.module.css
  src/images/icons/ic_kebab.svg
  src/loginModule.js
Labels: 미완성🫠

#226 [김가영] Sprint8
  package-lock.json
  package.json
  src/AddItem/AddItem.css
  src/AddItem/AddItem.tsx
  src/AddItem/FileInputImage.tsx
  src/AllItem/AllProductList.tsx
  src/App.js
  src/App.tsx
  src/Auth/Auth.css
  src/Auth/Login.tsx
  src/Auth/Signup.tsx
  src/Auth/useFormValidation.ts
  src/Auth/validateInput.js
  src/BestItem/BestProductList.tsx
  src/HomePage/HomePage.css
  src/HomePage/HomePage.tsx
  src/Items.js
  src/Items.tsx
  src/Pagination/Pagination.tsx
  src/ProductDetail/ProductComment.jsx
  src/ProductDetail/ProductComment.tsx
  src/ProductDetail/ProductDetail.css
  src/ProductDetail/ProductDetail.tsx
  src/ProductDetail/ProductDetailInfo.tsx
  src/ProductDetail/ProductInquiry.tsx
  src/ProductItem.css
  src/ProductItem.tsx
  src/api.ts
  src/headers/Header.tsx
  src/headers/header.css
  src/images/bottom.png
  src/images/example.png
  src/images/eye.png
  src/images/facebook.png
  src/images/google-logo.png
  src/images/hidden.png
  src/images/hot-item.png
  src/images/instagram.png
  src/images/kakao-logo.png
  src/images/logo-mobile.png
  src/images/logo.png
  src/images/logo2X.png
  src/images/register.png
  src/images/search.png
  src/images/top.png
  src/images/twitter.png
  src/images/youtube.png
  src/index.tsx
  src/react-app-env.d.ts
  src/reset.css
  tsconfig.json
Labels: 매운맛🔥

#238 [최예원] Sprint9
  .github/pull_request_template.md
  .gitignore
  app/api/articles.ts
  app/boards/layout.tsx
  app/boards/page.tsx
  app/layout.tsx
  app/page.tsx
  components/Board/BestArticleCard.tsx
  components/Board/PrintAllArticles.tsx
  components/Board/PrintBestArticles.tsx
  components/Footer.tsx
  components/Header.tsx
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  postcss.config.js
  postcss.config.mjs
  public/favicon.ico
  public/images/home/bottom-banner-image.png
  public/images/home/feature1-image.png
  public/images/home/feature2-image.png
  public/images/home/feature3-image.png
  public/images/home/hero-image.png
  public/images/icons/arrow_left.svg
  public/images/icons/arrow_right.svg
  public/images/icons/eye-invisible.svg
  public/images/icons/eye-visible.svg
  public/images/icons/ic_back.svg
  public/images/icons/ic_heart.svg
  public/images/icons/ic_kebab.svg
  public/images/icons/ic_medal.svg
  public/images/icons/ic_plus.svg
  public/images/icons/ic_search.svg
  public/images/icons/ic_sort.svg
  public/images/icons/ic_x.svg
  public/images/icons/img_badge.svg
  public/images/logo/logo-text.svg
  public/images/logo/logo.svg
  public/images/social/facebook-logo.svg
  public/images/social/google-logo.png
  public/images/social/instagram-logo.svg
  public/images/social/kakao-logo.png
  public/images/social/twitter-logo.svg
  public/images/social/youtube-logo.svg
  public/images/ui/empty-comments.svg
  public/images/ui/ic_profile.svg
  public/next.svg
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
  tailwind.config.js
  tailwind.config.ts
  tsconfig.json
  types/articleTypes.ts
Labels: 매운맛🔥, 미완성🫠

#241 [하유리] Sprint9
  .gitignore
  README.md
  components/BestPost.js
  components/BestPost.module.css
  components/Bulletin.js
  components/Bulletin.module.css
  components/Dropdown.js
  components/Dropdown.module.css
  components/Nav.js
  components/Nav.module.css
  components/SearchForm.js
  components/SearchForm.module.css
  font/ROKAF-Sans-Bold.woff
  font/ROKAF-Sans-Medium.woff
  jsconfig.json
  lib/axios.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/boards.js
  pages/index.js
  pages/items.js
  public/image/bestPostImg.png
  public/image/dropdownIcon.svg
  public/image/likeIcon.svg
  public/image/pandaMarketLogo.svg
  public/image/profileImg.svg
  public/image/searchIcon.svg
  styles/Home.module.css
  styles/global.css
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#235 [이태진] Sprint8
  .eslintrc.cjs
  package-lock.json
  package.json
  src/Main.tsx
  src/api.ts
  src/assets/icons/ic_facebook.svg
  src/assets/icons/ic_google.svg
  src/assets/icons/ic_instagram.svg
  src/assets/icons/ic_kakaotalk.svg
  src/assets/icons/ic_twitter.svg
  src/assets/icons/ic_visible_off.svg
  src/assets/icons/ic_visible_on.svg
  src/assets/icons/ic_youtube.svg
  src/assets/images/img_hot_item.png
  src/assets/images/img_logo_m.png
  src/assets/images/img_one_panda.png
  src/assets/images/img_register.png
  src/assets/images/img_search.png
  src/assets/images/img_two_panda.png
  src/components/App.tsx
  src/components/BestProductList.tsx
  src/components/Button.jsx
  src/components/Button.tsx
  src/components/CommentList.tsx
  src/components/FileInput.jsx
  src/components/FileInput.tsx
  src/components/Pagination.tsx
  src/components/ProductController.tsx
  src/components/ProductDetail.tsx
  src/components/ProductList.tsx
  src/components/SelectBox.tsx
  src/components/Tag.jsx
  src/components/Tag.tsx
  src/components/TopNavigation.tsx
  src/index.tsx
  src/pages/AddItem.tsx
  src/pages/Home.tsx
  src/pages/Item.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/SignUp.tsx
  src/pages/UsedMarket.tsx
  src/react-app-env.d.ts
  src/scripts/login.ts
  src/scripts/modules/formChecking.ts
  src/scripts/modules/inputWarning.ts
  src/scripts/modules/pwVisibility.ts
  src/scripts/modules/validationMsg.ts
  src/scripts/modules/validationUtils.ts
  src/scripts/modules/warningManager.ts
  src/scripts/signup.ts
  src/styledComponets/ImgInput.ts
  src/styles/Home.scss
  src/styles/Login.scss
  src/styles/SignUp.scss
  src/types/comment.ts
  src/types/product.ts
  src/utils/elapsedTime.ts
  tsconfig.json
Labels: 매운맛🔥

#237 [김가영] Sprint9
  components/BestListForm.module.css
  components/BestListForm.tsx
  components/Dropdown.tsx
  components/Dropwdown.module.css
  components/Header.module.css
  components/Header.tsx
  components/ListForm.module.css
  components/ListForm.tsx
  components/SearchForm.module.css
  components/SearchForm.tsx
  lib/api.ts
  lib/axios.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/[title].tsx
  pages/api/hello.ts
  pages/boards.tsx
  pages/index.tsx
  pages/search.tsx
  public/arrow_down.svg
  public/favicon.ico
  public/heart.svg
  public/logo.svg
  public/medal_icon.svg
  public/next.svg
  public/search.svg
  public/sort.svg
  public/userBtn.svg
  public/vercel.svg
  styles/Home.module.css
  styles/boards.module.css
  styles/global.css
  styles/globals.css
  tsconfig.json
Labels: 매운맛🔥

#240 [김가영] Sprint8
  src/AddItem/AddItem.tsx
  src/AllItem/AllProductList.tsx
  src/Auth/Auth.css
  src/Auth/Login.tsx
  src/Auth/Signup.tsx
  src/Auth/useFormValidation.ts
  src/Auth/validateInput.js
  src/BestItem/BestProductList.tsx
  src/Home.jsx
  src/ProductDetail/ProductDetailInfo.tsx
  src/api.ts
Labels: 매운맛🔥

#251 [최예원] sprint10
  api/articles.ts
  app/addboard/page.tsx
  app/boards/[id]/page.tsx
  app/boards/page.tsx
  app/layout.tsx
  app/page.tsx
  assets/fonts/PretendardVariable.woff2
  assets/images/icons/ic_heart.svg
  assets/images/ui/empty-reply.svg
  components/Board/AllArticleCard.tsx
  components/Board/AllArticleList.tsx
  components/Board/ArticleComment.tsx
  components/Board/BestArticleCard.tsx
  components/Board/BestArticleList.tsx
  components/Button.module.css
  components/Button.tsx
  components/FileInput.tsx
  components/Footer.tsx
  components/Header.tsx
  components/OrderDropdown.tsx
  hooks/useResize.ts
  next.config.js
  package-lock.json
  package.json
  styles/Footer.css
  styles/Homepage.css
  tailwind.config.ts
  types/article.ts
  types/form.ts
  utils/formatTimeDiff.ts
Labels: 매운맛🔥

#249 [고용빈] Sprint10
  .gitignore
  assets/icons/ic_arrow_down.svg
  assets/icons/ic_back.svg
  assets/icons/ic_heart.svg
  assets/icons/ic_kebab.svg
  assets/icons/ic_plus.svg
  assets/icons/ic_profile.svg
  assets/icons/ic_search.svg
  assets/icons/ic_sort.svg
  assets/icons/logo/logo.svg
  assets/icons/logo/mobile-logo.svg
  assets/images/img_badge.png
  assets/images/img_reply_empty.png
  components/Header/components/List/index.tsx
  components/Header/components/List/styles.module.scss
  components/Header/components/Logo/index.tsx
  components/Header/components/Logo/styles.module.scss
  components/Header/components/ProfileImage/index.tsx
  components/Header/components/ProfileImage/styles.module.scss
  components/Header/index.tsx
  components/Header/styles.module.scss
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/addboard/index.tsx
  pages/addboard/styles.module.scss
  pages/api/articles.ts
  pages/api/axiosInstance.ts
  pages/api/hello.ts
  pages/boards/[id]/components/Comment/index.tsx
  pages/boards/[id]/components/Comment/styles.module.scss
  pages/boards/[id]/components/NotComment/index.tsx
  pages/boards/[id]/components/NotComment/styles.module.scss
  pages/boards/[id]/index.tsx
  pages/boards/[id]/styles.module.scss
  pages/boards/components/All/AllPost/index.tsx
  pages/boards/components/All/AllPost/styles.module.scss
  pages/boards/components/All/Dropdown/index.tsx
  pages/boards/components/All/Dropdown/styles.module.scss
  pages/boards/components/All/index.tsx
  pages/boards/components/All/styles.module.scss
  pages/boards/components/Best/BestPost/index.tsx
  pages/boards/components/Best/BestPost/styles.module.scss
  pages/boards/components/Best/index.tsx
  pages/boards/components/Best/styles.module.scss
  pages/boards/index.tsx
  pages/boards/styles.module.scss
  pages/index.tsx
  styles/Home.module.css
  styles/color.scss
  styles/common.scss
  styles/globals.css
  styles/globals.scss
  styles/import.scss
  tsconfig.json
Labels: 매운맛🔥

#255 [하유리] Sprint10
  assets/images/addImgIcon.svg
  assets/images/backIcon.svg
  assets/images/bestPostImg.png
  assets/images/commentEmptyImg.png
  assets/images/dropdownIcon.svg
  assets/images/dropdownIcon_basic.svg
  assets/images/dropdownIcon_mobile.svg
  assets/images/kebabIcon.svg
  assets/images/likeIcon.svg
  assets/images/notFoundIcon.png
  assets/images/pandaMarketLogo.png
  assets/images/pandamarketLogoMobile.png
  assets/images/profileImg.svg
  assets/images/searchIcon.svg
  components/ActiveBtn.js
  components/ActiveBtn.module.css
  components/BestPost.js
  components/BestPost.module.css
  components/Bulletin.js
  components/Comment.js
  components/Comment.module.css
  components/Container.js
  components/Container.module.css
  components/Dropdown.js
  components/Dropdown.module.css
  components/FileInput.js
  components/Nav.js
  components/Nav.module.css
  components/NormalPost.js
  components/NormalPost.module.css
  components/SearchForm.js
  components/SearchForm.module.css
  font/ROKAF-Sans-Bold.woff
  font/ROKAF-Sans-Medium.woff
  next.config.mjs
  package-lock.json
  package.json
  pages/404.js
  pages/_app.js
  pages/_app.tsx
  pages/_document.tsx
  pages/addboard.js
  pages/board/[id].js
  pages/boards.js
  pages/index.tsx
  public/image/bestPostImg.png
  public/image/likeIcon.svg
  public/image/pandaMarketLogo.svg
  styles/404.module.css
  styles/FileInput.module.css
  styles/addboard.module.css
  styles/board.module.css
  styles/global.css
  styles/globals.css
  tsconfig.json
  utils/formatDate.js
  utils/isFormValid.js
Labels: 매운맛🔥, 미완성🫠

#243 [김당찬] Sprint9
  components/BestPost.module.css
  components/BestPost.tsx
  components/GeneralPost.module.css
  components/GeneralPost.tsx
  components/Header.module.css
  components/Header.tsx
  components/SearchForm.module.css
  components/SearchForm.tsx
  components/SelectBtn.module.css
  components/SelectBtn.tsx
  lib/api.ts
  lib/type.ts
  lib/useDevice.ts
  lib/useWindowSize.ts
  next.config.js
  pages/404.tsx
  pages/_app.tsx
  pages/board.tsx
  pages/index.tsx
  public/favicon.ico
  public/ic_arrow_down.svg
  public/ic_heart.svg
  public/ic_profile.svg
  public/ic_search.svg
  public/ic_sort.svg
  public/img_badge.svg
  public/logo.svg
  public/logo_mobile.svg
  public/next.svg
  public/vercel.svg
  styles/404.module.css
  styles/Home.module.css
  styles/board.module.css
  styles/globals.css
  styles/reset.css
Labels: 매운맛🔥

#246 [김가영] Sprint10
  components/BestListForm.tsx
  components/BoardComment.tsx
  components/BoardCommentList.tsx
  components/BoardDetail.module.css
  components/BoardDetailInfo.tsx
  components/Dropdown.tsx
  components/Dropwdown.module.css
  components/Header.tsx
  components/ListForm.tsx
  components/SearchForm.tsx
  components/type.ts
  lib/api.ts
  lib/axios.ts
  pages/addboard.tsx
  pages/api/[title].tsx
  pages/board/[id].tsx
  pages/board/index.tsx
  pages/search.tsx
  public/back.svg
  public/kebab.svg
  public/plus.svg
  public/profile.svg
  public/reply_empty.svg
  styles/addboard.module.css
  styles/board.module.css
Labels: 매운맛🔥

#248 [이태진] Sprint9
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  components/Button/index.module.scss
  components/Button/index.tsx
  components/Header/index.module.scss
  components/Header/index.tsx
  components/ResponsiveImage/index.module.scss
  components/ResponsiveImage/index.tsx
  constants/index.ts
  containers/board/Article/index.module.scss
  containers/board/Article/index.tsx
  containers/board/BestAticle/index.module.scss
  containers/board/BestAticle/index.tsx
  containers/board/SearchBar/index.module.scss
  containers/board/SearchBar/index.tsx
  containers/board/SelectBox/index.module.scss
  containers/board/SelectBox/index.tsx
  hooks/useResponsive.ts
  libs/axiosInstance.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/board/index.module.scss
  pages/board/index.tsx
  pages/index.tsx
  pages/items/index.module.scss
  pages/items/index.tsx
  public/favicon.ico
  public/images/badge-best.png
  public/images/logo-letters.png
  public/images/logo-small.png
  public/index.ts
  public/next.svg
  public/svgs/arrow-down.svg
  public/svgs/like-heart.svg
  public/svgs/magnifier.svg
  public/svgs/sort.svg
  public/svgs/user-profile.svg
  public/vercel.svg
  services/articles.ts
  styles/Home.module.css
  styles/_base.module.scss
  styles/_reset.module.scss
  styles/animations.scss
  styles/globals.css
  styles/globals.scss
  styles/mixins/_flexbox.scss
  styles/mixins/_index.scss
  styles/mixins/_position.scss
  styles/mixins/_responsive.scss
  styles/variables.scss
  types/article.d.ts
  types/responsive-image.d.ts
  types/select-order.d.ts
  utils/dateFormat.ts
Labels: 매운맛🔥

#250 [장아영] Sprint 9
  .gitignore
  assets/icons/ic_like.svg
  assets/icons/ic_search.svg
  assets/icons/ic_sort.svg
  assets/icons/logo.svg
  assets/icons/logo_mobile.svg
  assets/icons/profileImg.svg
  assets/images/best_badge.svg
  components/Header/Logo/index.tsx
  components/Header/Logo/styles.module.scss
  components/Header/MenuTab/index.tsx
  components/Header/MenuTab/styles.module.scss
  components/Header/Profile/index.tsx
  components/Header/Profile/style.module.scss
  components/Header/index.tsx
  components/Header/styles.module.scss
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/Api.ts
  pages/api/hello.ts
  pages/boards/components/BestPosts/BestPostElement/index.tsx
  pages/boards/components/BestPosts/BestPostElement/styles.module.scss
  pages/boards/components/BestPosts/index.tsx
  pages/boards/components/BestPosts/styles.module.scss
  pages/boards/components/Posts/Button/index.tsx
  pages/boards/components/Posts/Button/styles.module.scss
  pages/boards/components/Posts/DropDown/index.tsx
  pages/boards/components/Posts/DropDown/styles.module.scss
  pages/boards/components/Posts/DropDownMobile/index.tsx
  pages/boards/components/Posts/DropDownMobile/styles.module.scss
  pages/boards/components/Posts/Input/index.tsx
  pages/boards/components/Posts/Input/styles.module.scss
  pages/boards/components/Posts/PostElement/index.tsx
  pages/boards/components/Posts/PostElement/styles.module.scss
  pages/boards/components/Posts/index.tsx
  pages/boards/components/Posts/styles.module.scss
  pages/boards/index.tsx
  pages/boards/styles.module.scss
  pages/index.tsx
  styles/Home.module.css
  styles/color.scss
  styles/common.scss
  styles/font.scss
  styles/globals.css
  styles/globals.scss
  styles/import.scss
  tsconfig.json
Labels: 매운맛🔥

#253 [김도용] Sprint 9
  next.config.js
  pages/api/hello.ts
  pages/index.tsx
  public/assets/icons/bestBadge.svg
  public/assets/icons/dropDownArrow.svg
  public/assets/icons/favicon.ico
  public/assets/icons/likeDisabled.svg
  public/assets/icons/logo.svg
  public/assets/icons/search.svg
  public/assets/icons/userProfile.svg
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/axiosPanda.ts
  src/pages/board.tsx
  src/pages/components/BestPostList.tsx
  src/pages/components/Button.tsx
  src/pages/components/Header.tsx
  src/pages/components/PostList.tsx
  src/pages/index.tsx
  src/styles/BestPostList.module.css
  src/styles/Button.module.css
  src/styles/Header.module.css
  src/styles/Home.module.css
  src/styles/PostList.module.css
  src/styles/globals.css
  src/utils.ts
  styles/Home.module.css
  styles/globals.css
Labels: 매운맛🔥

#258 [황병선]Sprint9
  components/BestPostCard/BestPostCard.jsx
  components/BestPostCard/BestPostCard.module.scss
  components/BestPostsSection/BestPostsSection.jsx
  components/BestPostsSection/BestPostsSection.module.scss
  components/DropDown/DropDown.jsx
  components/DropDown/DropDown.module.scss
  components/Header/Header.jsx
  components/Header/Header.module.css
  components/PostCard/PostCard.jsx
  components/PostCard/PostCard.module.scss
  components/PostsSection/PostSection.jsx
  components/PostsSection/PostSection.module.scss
  components/api.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.jsx
  pages/_app.tsx
  pages/_document.jsx
  pages/api/hello.ts
  pages/boards/index.jsx
  pages/boards/index.module.scss
  pages/index.jsx
  pages/index.tsx
  public/favicon.ico
  public/ic_arrow_down.svg
  public/ic_heart.svg
  public/ic_medal.svg
  public/logo_pandamarket.svg
  public/next.svg
  public/vercel.svg
  styles/Home.module.css
  styles/common.css
  styles/globals.css
  styles/reset.css
  tsconfig.json
Labels: 미완성🫠

#263 [석지인] Sprint 10
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  src/app/addboard/layout.tsx
  src/app/addboard/page.tsx
  src/app/boards/layout.tsx
  src/app/boards/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/AllArticlesSection.tsx
  src/components/ArticleCard.tsx
  src/components/BestArticleCard.tsx
  src/components/BestArticlesSection.tsx
  src/components/NavBar.tsx
  src/lib/axios.ts
  src/lib/requests.ts
  src/styles/NotFound.module.css
  src/styles/globals.css
  src/types/articleTypes.ts
  tsconfig.json
Labels: 미완성🫠

#266 [고용빈] Sprint10-2
  .env
  .gitignore
  assets/icons/ic_cancel.svg
  assets/images/img_badge.png
  assets/images/img_badge.svg
  next.config.js
  package-lock.json
  package.json
  pages/addboard/index.tsx
  pages/addboard/styles.module.scss
  pages/api/articles.ts
  pages/api/axiosInstance.ts
  pages/boards/[id]/components/Comment/index.tsx
  pages/boards/[id]/components/Comment/styles.module.scss
  pages/boards/[id]/index.tsx
  pages/boards/components/All/AllPost/index.tsx
  pages/boards/components/All/AllPost/styles.module.scss
  pages/boards/components/All/Dropdown/index.tsx
  pages/boards/components/All/Dropdown/styles.module.scss
  pages/boards/components/All/index.tsx
  pages/boards/components/Best/BestArticleItem/index.tsx
  pages/boards/components/Best/BestArticleItem/styles.module.scss
  pages/boards/components/Best/index.tsx
  pages/boards/components/Best/styles.module.scss
  pages/boards/index.tsx
  services/articles.ts
  services/axiosInstance.ts
  styles/color.scss
  styles/globals.scss
Labels: 매운맛🔥

#265 [김당찬] Sprint10
  components/BestPost.tsx
  components/BoardDetailComments.module.css
  components/BoardDetailComments.tsx
  components/BoardDetailInfo.module.css
  components/BoardDetailInfo.tsx
  components/BoardDetailWrite.module.css
  components/BoardDetailWrite.tsx
  components/GeneralPost.tsx
  components/Header.module.css
  components/Header.tsx
  components/SearchForm.tsx
  components/SelectBtn.tsx
  constants/constants.ts
  lib/api.ts
  lib/type.ts
  lib/useDevice.ts
  pages/404.tsx
  pages/addboard.tsx
  pages/board/[id].tsx
  pages/board/index.tsx
  pages/index.tsx
  public/Img_reply_empty.svg
  public/ic_X.svg
  public/ic_X_hover.svg
  public/ic_back.svg
  public/ic_heart_2.svg
  public/ic_kebab.svg
  public/ic_plus.svg
  styles/addboard.module.css
  styles/boardDetail.module.css
Labels: 매운맛🔥

#267 [서미영] Sprint10
  components/board/BoardDetailArticle.module.scss
  components/board/BoardDetailArticle.tsx
  components/board/BoardDetailConfig.ts
  components/boards/AllArticleItem.tsx
  components/boards/AllArticleList.tsx
  components/boards/BestArticleItem.tsx
  components/boards/BestArticleList.tsx
  components/layout/Button.tsx
  components/layout/Comment.tsx/Comment.tsx
  components/layout/Comment.tsx/CommentsSection.tsx
  components/layout/Comment.tsx/Commtent.module.scss
  components/layout/Comment.tsx/GoBackToListButton.tsx
  components/layout/Dropdown.tsx
  components/layout/Dropdown/Dropdown.module.scss
  components/layout/Dropdown/Dropdown.tsx
  components/layout/Dropdown/SortDropdown.module.scss
  components/layout/Dropdown/SortDropdown.tsx
  components/layout/FileInput/FileInput.module.scss
  components/layout/FileInput/FileInput.tsx
  components/layout/Header/Header.tsx
  components/layout/RegisterForm/InputField.module.scss
  components/layout/RegisterForm/InputField.tsx
  components/layout/RegisterForm/RegisterForm.module.scss
  components/layout/RegisterForm/RegisterForm.tsx
  components/layout/RegisterForm/registerConfig.ts
  constants/deviceSizesConstants.ts
  constants/orderConstants.ts
  hooks/useClickOutside.ts
  hooks/useDeviceType.ts
  lib/articleApi.ts
  pages/addboard/index.tsx
  pages/board/[id].tsx
  pages/boards/index.tsx
  public/images/icons/Img_reply_empty.svg
  public/images/icons/no_img.svg
  styles/reset.css
  types/articleTypes.ts
  types/commonTypes.ts
  types/orderTypes.ts
  types/registerTypes.ts
  types/uiTypes.ts
  utils/Utils.ts
Labels: 매운맛🔥

#261 [김예준] Sprint10
  next.config.mjs
  public/svgs/comment.svg
  public/svgs/plus.svg
  public/svgs/seemore.svg
  src/components/Button/Button.module.scss
  src/components/DropDown/DropDown.tsx
  src/components/SearchBar/SearchBar.module.scss
  src/components/SearchBar/SearchBar.tsx
  src/components/Spinner/Spinner.module.scss
  src/components/Spinner/Spinner.tsx
  src/containers/boards/Article/Article.module.scss
  src/containers/boards/Article/Article.tsx
  src/containers/boards/Article/ArticleList.tsx
  src/containers/boards/BestArticle/BestArticle.module.scss
  src/containers/boards/BestArticle/BestArticle.tsx
  src/containers/boards/BestArticle/BestArticleList.tsx
  src/containers/boards/CreateArticle/CreateArticle.module.scss
  src/containers/boards/CreateArticle/CreateArticle.tsx
  src/containers/borads-detail/AddComment/AddComment.module.scss
  src/containers/borads-detail/AddComment/AddComment.tsx
  src/containers/borads-detail/ArticleDetail/ArticleDetail.module.scss
  src/containers/borads-detail/ArticleDetail/ArticleDetail.tsx
  src/containers/borads-detail/Comment/Comment.module.scss
  src/containers/borads-detail/Comment/Comment.tsx
  src/hooks/useFetechData.ts
  src/interfaces/Comment.interface.ts
  src/lib/axios.ts
  src/pages/boards.tsx
  src/pages/boards/[id].tsx
  src/pages/boards/create.tsx
  src/pages/boards/index.tsx
  src/styles/global.scss
Labels: 매운맛🔥

#268 [최민경] Sprint10
  components/CommentForm.module.scss
  components/CommentForm.tsx
  components/Dropdown.module.scss
  components/Input.module.scss
  components/Kebab.tsx
  components/Logo.tsx
  components/ProfileImage.tsx
  components/SearchForm.tsx
  components/board/Board.module.scss
  components/board/Board.tsx
  components/board/Like.tsx
  components/button/Button.module.scss
  components/button/Button.tsx
  components/comment/Comment.module.scss
  components/comment/Comment.tsx
  components/comment/CommentList.tsx
  components/input/FileInput.tsx
  components/input/Input.module.scss
  components/input/Input.tsx
  components/input/InputTextArea.tsx
  components/input/SearchInput.tsx
  components/post/BestBadge.module.scss
  components/post/BestPost.tsx
  components/post/BestPostList.tsx
  components/post/Post.module.scss
  components/post/PostImage.tsx
  components/post/PostList.tsx
  next.config.js
  package-lock.json
  package.json
  pages/addboard.tsx
  pages/board/[id].tsx
  pages/boards.tsx
  public/images/Img_reply_empty.svg
  public/images/ic_back.svg
  public/images/ic_cancel.svg
  public/images/ic_kebab.svg
  public/images/ic_plus.svg
  styles/AddBoard.module.scss
  styles/common/fonts.scss
  styles/index.scss
  types/post.d.ts
  types/type.d.ts
  utils/checkJosa.tsx
  utils/elapsedTime.tsx
Labels: 매운맛🔥

#270 [장아영] Sprint 10
  assets/icons/ic_delete.svg
  assets/icons/ic_kebab.svg
  assets/icons/ic_plus.png
  assets/icons/slash.svg
  components/Header/MenuTab/index.tsx
  components/Header/MenuTab/styles.module.scss
  package-lock.json
  package.json
  pages/addboard/index.tsx
  pages/addboard/styles.module.scss
  pages/boards/[id]/components/Comment/index.tsx
  pages/boards/[id]/components/Comment/styles.module.scss
  pages/boards/[id]/components/NoComment/index.tsx
  pages/boards/[id]/components/NoComment/style.module.scss
  pages/boards/[id]/index.tsx
  pages/boards/[id]/styles.module.scss
  pages/boards/components/BestPosts/BestPostElement/index.tsx
  pages/boards/components/BestPosts/BestPostElement/styles.module.scss
  pages/boards/components/BestPosts/index.tsx
  pages/boards/components/BestPosts/styles.module.scss
  pages/boards/components/Posts/Button/styles.module.scss
  pages/boards/components/Posts/DropDownMobile/index.tsx
  pages/boards/components/Posts/Input/styles.module.scss
  pages/boards/components/Posts/PostElement/index.tsx
  pages/boards/components/Posts/PostElement/styles.module.scss
  pages/boards/components/Posts/index.tsx
  pages/boards/components/Posts/styles.module.scss
  styles/color.scss
  styles/globals.scss
  styles/import.scss
Labels: 매운맛🔥, 미완성🫠

#273 [황병선] Sprint10
  components/BestPostCard/BestPostCard.tsx
  components/BestPostsSection/BestPostsSection.tsx
  components/CommentForm/CommentForm.module.scss
  components/CommentForm/CommentForm.tsx
  components/PostCard/PostCard.tsx
  components/PostDetailSection/PostDetailSection.module.scss
  components/PostDetailSection/PostDetailSection.tsx
  components/PostForm/PostForm.module.scss
  components/PostForm/PostForm.tsx
  components/PostsSection/PostSection.tsx
  components/api.js
  components/api.ts
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
  pages/addboard/index.module.scss
  pages/addboard/index.tsx
  pages/boards/[id]/index.module.scss
  pages/boards/[id]/index.tsx
  pages/boards/index.tsx
  pages/index.tsx
  public/ic_profile.svg
  public/icon_plus.svg
  public/icon_x-blue.svg
  tsconfig.json
Labels: 미완성🫠

#276 [김가영] Sprint11
  src/Auth/Auth.css
  src/Auth/Login.tsx
  src/Auth/Signup.tsx
  src/Auth/useFormValidation.ts
  src/BestItem/BestProductList.tsx
  src/HomePage/HomePage.tsx
  src/ProductItem.css
  src/api.ts
Labels: 매운맛🔥

#275 [김당찬] Sprint11
  src/App.css
  src/App.tsx
  src/Header.tsx
  src/assets/ic_mypage.svg
  src/pages/Authentication/Login.tsx
  src/pages/Authentication/Signup.tsx
  src/pages/Authentication/api.ts
  src/pages/Home/Home.css
  src/pages/Home/Home.tsx
  src/pages/Home/SocialBtn.tsx
  src/pages/Items/AddItem/AddItem.css
  src/pages/Items/AddItem/DescriptionInput.tsx
  src/pages/Items/AddItem/PriceInput.tsx
  src/pages/Items/AddItem/TagInput.tsx
  src/pages/Items/AddItem/TitleInput.tsx
  src/pages/Items/AllProductItem.tsx
  src/pages/Items/AllProductList.tsx
  src/pages/Items/BestProductItem.tsx
  src/pages/Items/BestProductList.tsx
  src/pages/Items/Items.css
  src/pages/Items/Pagination.tsx
  src/pages/Items/ProductDetail/ProductDetail.css
  src/pages/Items/ProductDetail/ProductDetail.tsx
  src/pages/Items/ProductDetail/ProductDetailComments.tsx
  src/pages/Items/ProductDetail/ProductDetailInfo.tsx
  src/pages/Items/ProductDetail/ProductDetailInquiry.tsx
  src/pages/Mypage/MyPage.css
  src/pages/Mypage/Mypage.tsx
  src/pages/NotFound/NotFound.css
  src/pages/NotFound/NotFound.tsx
  src/types/product.ts
Labels: 매운맛🔥

#278 [서미영] Sprint11
  components/board/BoardDetailArticle.module.scss
  components/board/BoardDetailArticle.tsx
  components/board/BoardDetailConfig.ts
  components/boards/AllArticleItem.tsx
  components/boards/AllArticleList.tsx
  components/boards/BestArticleItem.tsx
  components/boards/BestArticleList.tsx
  components/boards/Freeboard.module.scss
  components/layout/Auth/Auth.module.scss
  components/layout/Auth/AuthConfig.ts
  components/layout/Auth/AuthForm.tsx
  components/layout/Auth/EasyLogin.tsx
  components/layout/Auth/GoHomeLogo.tsx
  components/layout/Auth/InputField.tsx
  components/layout/Auth/TogglePassword.tsx
  components/layout/Button.module.scss
  components/layout/Button.tsx
  components/layout/Comment.tsx/Comment.tsx
  components/layout/Comment.tsx/CommentsSection.tsx
  components/layout/Comment.tsx/Commtent.module.scss
  components/layout/Comment.tsx/GoBackToListButton.tsx
  components/layout/Dropdown/Dropdown.tsx
  components/layout/Dropdown/SortDropdown.module.scss
  components/layout/Dropdown/SortDropdown.tsx
  components/layout/FileInput/FileInput.module.scss
  components/layout/FileInput/FileInput.tsx
  components/layout/Header/Header.tsx
  components/layout/RegisterForm/InputField.module.scss
  components/layout/RegisterForm/InputField.tsx
  components/layout/RegisterForm/RegisterForm.module.scss
  components/layout/RegisterForm/RegisterForm.tsx
  components/layout/RegisterForm/registerConfig.ts
  components/layout/SearchInput.module.scss
  components/layout/SearchInput.tsx
  ignup API
  lib/articleApi.ts
  lib/authApi.ts
  package-lock.json
  package.json
  pages/auth/[mode].tsx
  pages/board/[id].tsx
  pages/boards/index.tsx
  styles/_mixins.scss
  types/ArticleTypes.ts
  types/AuthTypes.ts
  types/CommonTypes.ts
  types/OrderTypes.ts
  types/RegisterTypes.ts
  types/UiTypes.ts
Labels: 매운맛🔥

#277 [고용빈] Sprint11
  .eslintrc.json
  assets/icons/social/ic_facebook.svg
  assets/icons/social/ic_instagram.svg
  assets/icons/social/ic_twitter.svg
  assets/icons/social/ic_youtube.svg
  assets/images/img_home_bottom.svg
  assets/images/img_home_top.svg
  assets/images/img_hotItem.png
  assets/images/img_register.png
  assets/images/img_search.png
  components/Header/components/List/index.tsx
  components/Header/components/Logo/index.tsx
  components/Header/components/ProfileImage/index.tsx
  components/Header/index.tsx
  next.config.js
  pages/addboard/index.tsx
  pages/addboard/styles.module.scss
  pages/boards/[id]/components/CommentItem/index.tsx
  pages/boards/[id]/components/CommentItem/styles.module.scss
  pages/boards/[id]/components/NoComment/index.tsx
  pages/boards/[id]/components/NoComment/styles.module.scss
  pages/boards/[id]/index.tsx
  pages/boards/[id]/styles.module.scss
  pages/boards/components/AllArticle/AllArticleItem/index.tsx
  pages/boards/components/AllArticle/AllArticleItem/styles.module.scss
  pages/boards/components/AllArticle/Dropdown/index.tsx
  pages/boards/components/AllArticle/Dropdown/styles.module.scss
  pages/boards/components/AllArticle/index.tsx
  pages/boards/components/AllArticle/styles.module.scss
  pages/boards/components/BestArticle/BestArticleItem/index.tsx
  pages/boards/components/BestArticle/BestArticleItem/styles.module.scss
  pages/boards/components/BestArticle/index.tsx
  pages/boards/components/BestArticle/styles.module.scss
  pages/boards/index.tsx
  pages/index.tsx
  pages/landing/index.tsx
  pages/landing/styles.module.scss
  services/articles.ts
  styles/color.scss
  styles/globals.scss
Labels: 매운맛🔥, 미완성🫠

#280 [최예원] Sprint11
  .gitignore
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/item.ts
  src/components/NavBar/NavBar.module.css
  src/components/NavBar/NavBar.tsx
  src/hooks/useResize.ts
  src/pages/ItemDetailPage/ItemDetailPage.module.css
  src/pages/ItemDetailPage/ItemDetailPage.tsx
  src/pages/ItemDetailPage/components/CommentSection.tsx
  src/pages/MarketPage/components/PrintAllItems.tsx
  src/pages/MarketPage/components/PrintBestItems.tsx
  src/pages/auth/LoginPage/LoginPage.tsx
  src/pages/auth/SignupPage/SignupPage.tsx
  src/pages/auth/components/ValidationInput.tsx
  src/utils/authValidation.ts
  vite.config.ts
Labels: 매운맛🔥
