Repository codeit-bootcamp-frontend/7-Sprint-Mission, pull requests merged in 2024-05, with the labels that each got.

#37 [고용빈] sprint1
  .DS_Store
  img/.DS_Store
  img/home/bottom-banner-image.png
  img/home/feature1-image.png
  img/home/feature2-image.png
  img/home/feature3-image.png
  img/home/hero-image.png
  img/logo/favicon.ico
  img/logo/panda-market-logo.png
  img/social/facebook-logo.svg
  img/social/instagram-logo.svg
  img/social/twitter-logo.svg
  img/social/youtube-logo.svg
  index.html
  main.css
Labels: 매운맛🔥

#63 [최예원] Sprint2
  .gitignore
  images/.DS_Store
  images/btn_visibility_off.png
  images/btn_visibility_on.png
  images/google-logo.png
  images/kakao-logo.png
  index.html
  package-lock.json
  package.json
  signin.html
  signup.html
  styles/global.css
  styles/reset.css
  styles/signin.css
  styles/style.css
Labels: 매운맛🔥

#42 [손권우] Sprint2
  css/define.css
  css/login.css
  css/style.css
  fonts/pretendard.css
  fonts/woff2/Pretendard-Black.woff2
  fonts/woff2/Pretendard-Bold.woff2
  fonts/woff2/Pretendard-ExtraBold.woff2
  fonts/woff2/Pretendard-ExtraLight.woff2
  fonts/woff2/Pretendard-Light.woff2
  fonts/woff2/Pretendard-Medium.woff2
  fonts/woff2/Pretendard-Regular.woff2
  fonts/woff2/Pretendard-SemiBold.woff2
  fonts/woff2/Pretendard-Thin.woff2
  image/ic_google.png
  image/ic_kakaotalk.png
  image/ic_visibility.svg
  image/ic_visibility_off.svg
  image/logo-big.png
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#43 [신지원] Sprint2
  faq.html
  images/bottom-banner-image.png
  images/bottom.png
  images/favicon.ico
  images/feature1-image.png
  images/feature2-image.png
  images/feature3-image.png
  images/hero-image.png
  images/img1.png
  images/img2.png
  images/img3.png
  images/logo.svg
  images/navi.png
  index.html
  items.html
  login.html
  logo/eyeclose.svg
  logo/favicon.ico
  logo/panda-market-logo.png
  logo/panda-market-logo.svg
  mission1.css
  privacy.html
  signup.html
  social/facebook-logo.svg
  social/googlelogo.svg
  social/instagram-logo.svg
  social/kakaologo.svg
  social/twitter-logo.svg
  social/youtube-logo.svg
  styles/global.css
  styles/home.css
  styles/login.css
  styles/signup.css
Labels: 매운맛🔥, 미완성🫠

#66 [정한주]Sprint2
  panda1/btn_visibility.png
  panda1/google_lg.png
  panda1/index.html
  panda1/kakao_lg.png
  panda1/login.html
  panda1/logo_L.png
  panda1/signup.html
  panda1/style.css
Labels: 매운맛🔥

#61 [장아영] Sprint2
  .DS_Store
  button.css
  color.css
  img/.DS_Store
  img/Img_home_01.png
  img/Img_home_02-1.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/Property 1=Typo.png
  img/btn_visibility_on_24px.png
  img/ic_X.png
  img/ic_facebook.png
  img/ic_google.png
  img/ic_instagram.png
  img/ic_instagram.svg
  img/ic_kakao.png
  img/ic_plus.png
  img/ic_profile.png
  img/ic_search.png
  img/ic_search_darker.png
  img/ic_sort.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/logo.png
  img/status=Default (1).png
  img/status=Default.png
  img/toplogo.png
  index/index.css
  index/index.html
  login.css
  login.html
  signup.css
  signup.html
Labels: 매운맛🔥

#55 [홍준기] Sprint2
  .DS_Store
  [홍준기]Library.css
  [홍준기]sprint 1 .css
  [홍준기]sprint 1.html
  image/.DS_Store
  image/Property 1=Variant3.png
  image/Vector.png
  image/google.png
  image/kakaoTalk.png
  login.css
  login.html
  signUp.css
  signUp.html
Labels: 매운맛🔥

#54 [김도용] Sprint2
  week2/button.css
  week2/colorSet.css
  week2/easyRem.css
  week2/fontPretendard.css
  week2/image/Img_home_01.png
  week2/image/Img_home_02.png
  week2/image/Img_home_03.png
  week2/image/Img_home_bottom.png
  week2/image/Img_home_top.png
  week2/image/ic_facebook.png
  week2/image/ic_google.png
  week2/image/ic_instagram.png
  week2/image/ic_kakao.png
  week2/image/ic_twitter.png
  week2/image/ic_youtube.png
  week2/image/logo.png
  week2/index.html
  week2/inputSet.css
  week2/sign.css
  week2/signEnable.js
  week2/signIn.html
  week2/signUp.html
  week2/style.css
Labels: 매운맛🔥

#48 [함다윤] sprint2
  .github/pull_request_template.md
  faq/faq.html
  images/etc/btn_visibility.png
  images/home/Img_home_01.png
  images/home/Img_home_02.png
  images/home/Img_home_03.png
  images/home/Img_home_bottom.png
  images/home/Img_home_top.png
  images/logo/Group19.png
  images/logo/favicon.ico
  images/logo/logo.png
  images/logo/panda-icon.png
  images/social/googlelogo.png
  images/social/ic_facebook.png
  images/social/ic_instagram.png
  images/social/ic_twitter.png
  images/social/ic_youtube.png
  images/social/kakaologo.png
  index.html
  items.html
  items/items.html
  login-signup/login.html
  login-signup/signup.html
  login-signup/style.css
  login.html
  privacy/privacy.html
  screencapture.png
  style.css
Labels: 매운맛🔥

#59 [김당찬] Sprint2
  images/Img_home_01.png
  images/Img_home_01@3x.png
  images/Img_home_02.png
  images/Img_home_02@3x.png
  images/Img_home_03.png
  images/Img_home_03@3x.png
  images/Img_home_bottom.png
  images/Img_home_bottom@3x.png
  images/btn_visibility_off_24px.svg
  images/google-icon.svg
  images/kakao-icon.svg
  images/logo.png
  images/logo@2x.png
  images/logo@3x.png
  index.css
  index.html
  pages/authentication/authentication.css
  pages/authentication/login.html
  pages/authentication/signup.html
  pages/faq/faq.html
  pages/items/items.html
  pages/login.html
  pages/privacy.html
  pages/privacy/privacy.html
  reset.css
  style.css
Labels: 매운맛🔥

#58 김가영[Sprint2]
  image/Group 19.png
  image/Img_home_01.png
  image/Img_home_02-1.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Property 1=Default (1).png
  image/Vector.png
  image/facebook.png
  image/google.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/logo@2x (1).png
  index.html
  login.html
  mission2-1.css
  mission2.css
  mission_1.css
  signup.html
Labels: 매운맛🔥

#71 [박재현] Sprint1
  img/home/bottom-banner-image.png
  img/home/feature1-image.png
  img/home/feature2-image.png
  img/home/feature3-image.png
  img/home/hero-image.png
  img/logo/favicon.ico
  img/logo/panda-market-logo.png
  img/social/facebook-logo.svg
  img/social/instagram-logo.svg
  img/social/twitter-logo.svg
  img/social/youtube-logo.svg
  index.html
  style.css
Labels: 매운맛🔥

#50 [이태진] Sprint 2
  images/icon/ic_facebook.png
  images/icon/ic_google.png
  images/icon/ic_instagram.png
  images/icon/ic_kakaotalk.png
  images/icon/ic_twitter.png
  images/icon/ic_visible_off.png
  images/icon/ic_youtube.png
  images/img/img_hot_item.png
  images/img/img_one_panda.png
  images/img/img_register.png
  images/img/img_search.png
  images/img/img_two_panda.png
  images/logo/logo_logo_m.png
  images/logo/logo_logo_s.png
  images/logo/logo_panda_face.png
  images/logo/logo_pandamarket.png
  index.html
  login/index.html
  login/style.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#51 [송효정] sprint2
  index.html
  login/index.html
  signup/index.html
  src/css/global.css
  src/css/home.css
  src/css/login.css
  src/img/common/logo.png
  src/img/common/logo_small.png
  src/img/login/btn_visibility_close.svg
  src/img/login/btn_visibility_open.svg
  src/img/login/social_login_google.png
  src/img/login/social_login_kakao.png
Labels: 매운맛🔥

#52 [정유승] sprint2
  faq.html
  image/bottom-banner-image.png
  image/favicon.ico
  image/home-image1.png
  image/home-image2.png
  image/home-image3.png
  image/ic_facebook@3x.png
  image/ic_instagram@3x.png
  image/ic_twitter@3x.png
  image/ic_youtube@3x.png
  image/main-image.png
  image/panda-market-logo.png
  index.html
  items.html
  privacy.html
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#53 [석지인] Sprint2
  faq/index.html
  images/ic_google.png
  images/ic_invisible-pw.png
  images/ic_kakaotalk.png
  images/ic_pandamarket-title.png
  images/ic_pandamarket.png
  images/ic_title.png
  images/ic_visible-pw.png
  images/img_home_hello-panda-alone.png
  images/img_home_hello-panda-together.png
  images/img_home_hot-item.png
  images/img_home_register.png
  images/img_home_search.png
  index.html
  items/index.html
  login/index.html
  login/index.js
  login/style.css
  privacy/index.html
  signup/index.html
  signup/index.js
  signup/style.css
  style.css
Labels: 매운맛🔥

#60 [황병선] Sprint2
  .DS_Store
  Images/.DS_Store
  Images/bottom-banner(panda-talking).png
  Images/home-content1.png
  Images/home-content2.png
  Images/home-content3.png
  Images/ic_facebook.png
  Images/ic_google.png
  Images/ic_instagram.png
  Images/ic_kakaotalk.png
  Images/ic_twitter.png
  Images/ic_visibility.png
  Images/ic_youtube.png
  Images/pandamarket-logo(1).png
  Images/pandamarket-logo.png
  Images/top-banner(panda-hello).png
  Pages/login.html
  Pages/signup.html
  Styles/reset.css
  Styles/style.css
  index.html
  style.css
Labels: 매운맛🔥, 미완성🫠

#65 [강한솔] Sprint2
  google.png
  kakao.png
  signup.html
  판다 마켓 로고.png
Labels: 매운맛🔥

#41 Basic 김예준 sprint2
  bottom.png
  faq.html
  image/home/image_home_01.png
  image/home/image_home_02.png
  image/home/image_home_03.png
  image/home/image_home_bottom.png
  image/home/image_home_top.png
  image/icon/eye-none.png
  image/icon/eye.png
  image/logo/favicon.ico
  image/logo/login.png
  image/logo/logo.png
  image/logo/search.png
  image/social/facebook.png
  image/social/google.png
  image/social/instagram.png
  image/social/kakao.png
  image/social/twitter.png
  image/social/youtube.png
  index.html
  items.html
  last.png
  privacy.html
  signin.html
  signup.html
  sprinter.html
  styles/auth.css
  styles/global.css
  styles/home.css
  top.png
Labels: 매운맛🔥

#77 [박재현] Sprint2
  img/icon/btn__visibility-off.svg
  img/icon/btn__visibility-on.svg
  img/icon/google.svg
  img/icon/kakao.svg
  index.html
  login.html
  signup.html
  styles/color.css
  styles/fonts.css
  styles/login-signup.css
  styles/main.css
  styles/reset.css
Labels: 매운맛🔥

#78 [고용빈] sprint2
  css/main.css
  css/reset.css
  css/signin.css
  css/signup.css
  img/icons/eye-invisible.svg
  img/icons/eye-visible.svg
  img/social/google-logo.png
  img/social/kakao-logo.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#64 [하유리] Sprint3
  css/index.css
  css/login.css
  css/signup.css
  css/style.css
  image/google_icon.png
  image/kakao_icon.png
  image/pandamarket_preview.jpg
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#93 [김당찬] Sprint3
  images/meta_image.png
  index.css
  index.html
  pages/authentication/authentication.css
  style.css
Labels: 매운맛🔥

#80 [최민경] Sprint3
  common/button.css
  common/color.css
  html/login.html
  html/signup.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/logo-text.png
  images/opengraph-img.png
  index.html
  js/login.js
  js/signup.js
  login.css
  style.css
Labels: 매운맛🔥

#82 [함다윤] sprint3
  .github/pull_request_template.md
  images/logo/logo.png
  images/logo/logo_withicon.png
  index.html
  login-signup/login.html
  login-signup/signup.html
  login-signup/style.css
  style.css
Labels: 매운맛🔥, 미완성🫠

#81 [이태진] Sprint3
  assets/icons/ic_facebook.svg
  assets/icons/ic_google.svg
  assets/icons/ic_instagram.svg
  assets/icons/ic_kakaotalk.svg
  assets/icons/ic_twitter.svg
  assets/icons/ic_visible_off.svg
  assets/icons/ic_visible_on.svg
  assets/icons/ic_youtube.svg
  assets/images/img_hot_item.png
  assets/images/img_logo_m.png
  assets/images/img_logo_s.png
  assets/images/img_one_panda.png
  assets/images/img_panda_face.png
  assets/images/img_register.png
  assets/images/img_search.png
  assets/images/img_two_panda.png
  css/common.css
  css/home.css
  css/login.css
  css/signup.css
  images/icon/ic_facebook.png
  images/icon/ic_google.png
  images/icon/ic_instagram.png
  images/icon/ic_kakaotalk.png
  images/icon/ic_twitter.png
  images/icon/ic_visible_off.png
  images/icon/ic_youtube.png
  images/logo/logo_panda_face.png
  images/logo/logo_pandamarket.png
  index.html
  login/index.html
  signup/index.html
Labels: 매운맛🔥

#91 [석지인] Sprint3
  README.md
  global.css
  images/buttons/btn_large.png
  images/buttons/btn_small.png
  images/icons/ic_facebook.png
  images/icons/ic_google.png
  images/icons/ic_instagram.png
  images/icons/ic_invisible-pw.png
  images/icons/ic_kakaotalk.png
  images/icons/ic_pandamarket-title.png
  images/icons/ic_pandamarket.png
  images/icons/ic_title.png
  images/icons/ic_twitter.png
  images/icons/ic_visible-pw.png
  images/icons/ic_youtube.png
  images/illustrations/illust_home_hello-panda-alone.png
  images/illustrations/illust_home_hello-panda-together.png
  images/illustrations/illust_home_hot-item.png
  images/illustrations/illust_home_register.png
  images/illustrations/illust_home_search.png
  index.html
  login-and-signup.css
  login/index.html
  netlify.toml
  publish/_redirects
  signup/index.html
  signup/style.css
  style.css
Labels: 미완성🫠

#94 [정유승]sprint3
  faq.html
  image/btn_visibility_off_24px.svg
  image/btn_visibility_on_24px.svg
  image/mainBanner/bottom-banner-image.png
  image/mainBanner/favicon.ico
  image/mainBanner/home-image1.png
  image/mainBanner/home-image2.png
  image/mainBanner/home-image3.png
  image/mainBanner/main-image.png
  image/mainBanner/panda-market-logo.png
  image/sns-logo/google-logo.png
  image/sns-logo/ic_facebook@3x.png
  image/sns-logo/ic_instagram@3x.png
  image/sns-logo/ic_twitter@3x.png
  image/sns-logo/ic_youtube@3x.png
  image/sns-logo/kakao-logo.png
  index.html
  items.html
  privacy.html
  signin.html
  signup.html
  styles/main.css
  styles/sign.css
  styles/style.css
Labels: 미완성🫠

#104 [홍준기] Sprint3
  .DS_Store
  .gitignore
  [홍준기]Library.css
  [홍준기]sprint 1 .css
  [홍준기]sprint 1.html
  index.html
  login.css
  login.html
  signUp.html
  style.css
Labels: 매운맛🔥, 미완성🫠

#96 [송효정] Sprint3
  index.html
  login/index.html
  signup/index.html
  src/css/global.css
  src/css/home.css
Labels: 매운맛🔥, 미완성🫠

#98 [김도용] sprint 3
  week3/assets/images/Img_home_01.png
  week3/assets/images/Img_home_02.png
  week3/assets/images/Img_home_03.png
  week3/assets/images/Img_home_bottom.png
  week3/assets/images/Img_home_top.png
  week3/assets/images/ic_facebook.png
  week3/assets/images/ic_google.png
  week3/assets/images/ic_instagram.png
  week3/assets/images/ic_kakao.png
  week3/assets/images/ic_twitter.png
  week3/assets/images/ic_youtube.png
  week3/assets/images/logo.png
  week3/assets/images/logo_icon.png
  week3/index.html
  week3/modules/css/button.css
  week3/modules/css/commonSign.css
  week3/modules/css/globals.css
  week3/modules/css/index.css
  week3/modules/css/indexDesktop.css
  week3/modules/css/indexMobile.css
  week3/modules/css/indexTablet.css
  week3/modules/css/inputSet.css
  week3/modules/css/signIn.css
  week3/modules/css/signUp.css
  week3/modules/js/signEnable.js
  week3/signIn.html
  week3/signUp.html
Labels: 매운맛🔥

#101 [정한주] Sprint3
  panda1/btn_login.png
  panda1/img/Img_home_01.png
  panda1/img/Img_home_02.png
  panda1/img/Img_home_03.png
  panda1/img/Img_home_bottom.png
  panda1/img/Img_home_top.png
  panda1/img/btn_visibility.png
  panda1/img/lg_fb.png
  panda1/img/lg_google.png
  panda1/img/lg_inst.png
  panda1/img/lg_kakao.png
  panda1/img/lg_twt.png
  panda1/img/lg_yt.png
  panda1/img/logo.png
  panda1/img/logo_L.png
  panda1/img/logo_panda.png
  panda1/img/preview.png
  panda1/index.html
  panda1/login.css
  panda1/login.html
  panda1/logo.png
  panda1/signup.html
  panda1/style.css
Labels: 매운맛🔥

#100 [황병선] Sprint3
  Images/.DS_Store
  Pages/login.html
  Pages/signup.html
  Styles/auth.css
  Styles/home.css
  Styles/reset.css
  index.html
Labels: 매운맛🔥

#107 [장아영] sprint3
  .DS_Store
  button.css
  index/index.css
  index/index.html
  login.css
  signup.css
  signup.html
Labels: 매운맛🔥

#86 [최주혁] sprint4
  assets/css/common.css
  assets/css/form.css
  assets/js/changeInputState.js
  assets/js/sign/validate.js
  assets/js/sign/validate/input/validateEmail.js
  assets/js/sign/validate/input/validateNickname.js
  assets/js/sign/validate/input/validatePassword.js
  assets/js/sign/validate/input/validatePasswordCheck.js
  assets/js/sign/validate/page/validateLogin.js
  assets/js/sign/validate/page/validateSign.js
  assets/js/sign/validate/validate.js
  assets/js/sign/visibility.js
  assets/js/user.js
  index.html
  pages/faq/index.html
  pages/items/index.html
  pages/login/index.html
  pages/privacy/index.html
  pages/signup/index.html
Labels: 매운맛🔥

#85 [서미영] Sprint4
  faq.html
  images/logo/btn_visibility_off.svg
  images/logo/btn_visibility_on.svg
  index.html
  login.html
  scripts/account.js
  scripts/authValidation.js
  scripts/constants.js
  scripts/togglePasswordVisibility.js
  signin.html
  signup.html
  styles/account.css
  styles/common.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#83 [김광호] Sprint3
  images/logo/panda-market-logo.svg
  index.html
  link.html
  login.html
  signup.html
  styles/global.css
  styles/home.css
  styles/login.css
Labels: 매운맛🔥

#79 [신지원] Sprint3
  index.html
  login.html
  signup.html
  styles/auth.css
  styles/global.css
  styles/home.css
  styles/signup.css
Labels: 매운맛🔥, 미완성🫠

#84 [하유리] sprint4
  css/index.css
  css/login.css
  css/signup.css
  index.html
  javascript/login.js
  javascript/signup.js
  login.html
  screenshot/landingPage_desktop.png
  screenshot/landingPage_mobile.png
  screenshot/landingPage_tablet.png
  screenshot/login_desktop.png
  screenshot/login_mobile.png
  screenshot/login_tablet.png
  screenshot/signup_desktop.png
  screenshot/signup_mobile.png
  screenshot/signup_tablet.png
  signup.html
Labels: 매운맛🔥

#110 [고용빈] sprint3
  .DS_Store
  css/main.css
  css/reset.css
  css/signin.css
  css/signup.css
  faq.html
  img/og/panda.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#109 [김가영] Sprint 3
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  css/auth.css
  css/index.css
  css/reset.css
  html/index.html
  html/login.html
  html/signup.html
  image/bottom.png
  image/example.png
  image/eye.png
  image/facebook.png
  image/google-logo.png
  image/google.png
  image/hot-item.png
  image/ic_facebook.png
  image/instagram.png
  image/kakao-logo.png
  image/logo.png
  image/logo2X.png
  image/no_eye.png
  image/register.png
  image/search.png
  image/top.png
  image/twitter.png
  image/youtube.png
  index.html
  login.html
  mission2-1.css
  mission2.css
  mission_1.css
  signup.html
Labels: 매운맛🔥

#75 [김예준] Sprint3
  image/logo/logo_mini.png
  image/logo/og.png
  index.html
  index.js
  signin.html
  signup.html
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#106 [서향] Sprint3
  faq.html
  htmls/faq.html
  htmls/login.html
  htmls/market.html
  htmls/privacy.html
  htmls/signup.html
  images/google.png
  images/kakaotalk.png
  images/panda-market-logo-mobile.png
  images/visibility_off.png
  images/visibility_on.png
  index.html
  login.html
  market.html
  privacy.html
  styles/accountinput.css
  styles/header.css
  styles/home.css
  test.txt
Labels: 매운맛🔥

#142 강효성 sprint4
  index.html
  login.html
  scripts/auth.js
  signup.html
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥, 미완성🫠

#112 [박재현] Sprint4
  index.html
  js/error-handler.js
  js/main.js
  js/utils.js
  js/validators.js
  login/index.html
  signup/index.html
  styles/color.css
  styles/login-signup.css
  styles/main.css
  styles/reset.css
Labels: 매운맛🔥

#115 [김광호] Sprint4
  images/home/btn-unvisibility_button.svg
  images/logo/panda-market-logo.svg
  images/logo/panda-market-pandalogo.svg
  index.html
  js/login.js
  js/signup.js
  login.html
  signin.html
  signup.html
  styles/global.css
  styles/login.css
Labels: 매운맛🔥

#119 [이태진] Sprint4
  css/common.css
  css/home.css
  css/login.css
  css/reset.css
  css/signup.css
  index.html
  login/index.html
  scripts/login.js
  scripts/modules/formChecking.js
  scripts/modules/inputWarning.js
  scripts/modules/pwVisibility.js
  scripts/modules/validationMsg.js
  scripts/modules/validationUtils.js
  scripts/modules/warningManager.js
  scripts/signup.js
  signup/index.html
Labels: 매운맛🔥

#133 [장아영] sprint4
  button.css
  index/index.css
  login.css
  login.html
  login_input.js
  signup.css
  signup.html
  signup_input.js
Labels: 매운맛🔥, 미완성🫠

#127 [고용빈] sprint4
  css/auth.css
  css/main.css
  css/reset.css
  css/signin.css
  img/logo/logo.png
  index.html
  js/validateLogin.js
  js/validateSignUp.js
  signin.html
  signup.html
Labels: 매운맛🔥

#122 [정한주] Sprint4
  panda1/.prettierrc
  panda1/img/btn_unvisible.svg
  panda1/img/btn_visibility.png
  panda1/img/btn_visible.svg
  panda1/img/lg_fb.png
  panda1/img/lg_fb.svg
  panda1/img/lg_inst.png
  panda1/img/lg_inst.svg
  panda1/img/lg_twt.png
  panda1/img/lg_twt.svg
  panda1/img/lg_yt.png
  panda1/img/lg_yt.svg
  panda1/img/logo.png
  panda1/img/logo.svg
  panda1/img/logo_panda.png
  panda1/img/logo_panda.svg
  panda1/index.html
  panda1/items.html
  panda1/login.css
  panda1/login.html
  panda1/login.js
  panda1/screenshot/mission1.png
  panda1/signin.html
  panda1/signup.html
  panda1/signup.js
  panda1/style.css
Labels: 매운맛🔥

#124 [홍준기] Sprint4
  .DS_Store
  .gitignore
  .prettierrc
  [홍준기]Library.css
  index.html
  login.css
  login.html
  login.js
  signUp.css
  signUp.html
  signUp.js
  style.css
Labels: 매운맛🔥

#131 Basic 함다윤 sprint4
  .github/pull_request_template.md
  images/etc/btn_visibility_off.svg
  images/etc/btn_visibility_on.svg
  index.html
  login-signup/index.js
  login-signup/login.html
  login-signup/nickname_error.js
  login-signup/pass_check_error.js
  login-signup/signup.html
  login-signup/style.css
  style.css
Labels: 매운맛🔥, 미완성🫠

#113 [김도용] Sprint4
  week4/assets/images/Img_home_01.png
  week4/assets/images/Img_home_02.png
  week4/assets/images/Img_home_03.png
  week4/assets/images/Img_home_bottom.png
  week4/assets/images/Img_home_top.png
  week4/assets/images/btn_visibility_off.svg
  week4/assets/images/btn_visibility_on.svg
  week4/assets/images/ic_facebook.png
  week4/assets/images/ic_google.png
  week4/assets/images/ic_instagram.png
  week4/assets/images/ic_kakao.png
  week4/assets/images/ic_twitter.png
  week4/assets/images/ic_youtube.png
  week4/assets/images/logo.png
  week4/assets/images/logo_icon.png
  week4/index.html
  week4/modules/css/button.css
  week4/modules/css/commonSign.css
  week4/modules/css/globals.css
  week4/modules/css/index.css
  week4/modules/css/indexDesktop.css
  week4/modules/css/indexMobile.css
  week4/modules/css/indexTablet.css
  week4/modules/css/inputSet.css
  week4/modules/css/signIn.css
  week4/modules/css/signUp.css
  week4/modules/js/commonSign.js
  week4/signIn.html
  week4/signUp.html
Labels: 매운맛🔥

#132 [손권우] sprint4
  css/define.css
  css/login.css
  css/style.css
  fonts/ROKAF Sans Bold.otf
  fonts/ROKAF Sans Medium.otf
  fonts/ROKAF Slab Serif Bold.otf
  fonts/ROKAF Slab Serif Medium.otf
  image/logo-meta.png
  image/logo-small.svg
  index.html
  javascript/login.js
  javascript/modules.js
  javascript/signup.js
  login.html
  signup.html
Labels: 매운맛🔥, 미완성🫠

#117 [김예준] Sprint4
  index.html
  script/auth.js
  script/index.js
  signin.html
  signup.html
  styles/auth.css
  styles/global.css
Labels: 매운맛🔥

#116 [김가영] Sprint 4
  css/auth.css
  css/index.css
  css/reset.css
  html/index.html
  html/login.html
  html/signup.html
  image/hidden.png
  image/logo-mobile.png
  js/validateInput.js
Labels: 매운맛🔥, 미완성🫠

#134 [김당찬] Sprint4
  images/btn_visibility_on_24px.svg
  pages/authentication/authentication.css
  pages/authentication/login.html
  pages/authentication/login.js
  pages/authentication/signup.html
  pages/authentication/signup.js
Labels: 매운맛🔥

#111 [임창기] Sprint__3
  index.js
  signup.css
  signup.html
  src/images/GooleIcon.png
  src/images/KakaoIcon.png
  src/images/closedEye.png
  src/images/logo.png
  src/images/openEye.png
  src/pages/faq/faq.css
  src/pages/faq/faq.html
  src/pages/index/assets/images/Img_home_01.png
  src/pages/index/assets/images/Img_home_02.png
  src/pages/index/assets/images/Img_home_03.png
  src/pages/index/assets/images/Img_home_bottom.png
  src/pages/index/assets/images/Img_home_top.png
  src/pages/index/assets/images/ic_facebook.png
  src/pages/index/assets/images/ic_instagram.png
  src/pages/index/assets/images/ic_twitter.png
  src/pages/index/assets/images/ic_youtube.png
  src/pages/index/assets/images/판다 얼굴.png
  src/pages/index/index.css
  src/pages/index/index.html
  src/pages/items/items.css
  src/pages/items/items.html
  src/pages/privacy/privacy.css
  src/pages/privacy/privacy.html
  src/pages/signin/signin.css
  src/pages/signin/signin.html
  src/pages/signup/signup.css
  src/pages/signup/signup.html
Labels: 매운맛🔥

#129 [황병선] Sprint4
  .DS_Store
  Images/ic_nonvisibility.png
  Images/ic_visibility.png
  Pages/login.html
  Pages/signup.html
  Styles/auth.css
  scripts/auth.js
Labels: 매운맛🔥

#144 [최주혁] sprint4-2
  assets/css/common.css
  assets/js/changeInputState.js
  assets/js/isEmpty.js
  assets/js/sign/validate/input/validateEmail.js
  assets/js/sign/validate/input/validateNickname.js
  assets/js/sign/validate/input/validatePassword.js
  assets/js/sign/validate/input/validatePasswordCheck.js
  assets/js/sign/validate/validate.js
  assets/js/user.js
Labels: 매운맛🔥

#136 [임창기] Sprint4
  src/components/EmailValidation.js
  src/pages/index/index.html
  src/pages/items/items.html
  src/pages/signin/signin.css
  src/pages/signin/signin.html
  src/pages/signin/signin.js
  src/pages/signup/signup.css
  src/pages/signup/signup.html
  src/pages/signup/signup.js
Labels: 매운맛🔥

#138 [최예원] Sprint4
  index.html
  js/button-visibility.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
  styles/auth.css
  styles/global.css
  styles/style.css
Labels: 매운맛🔥

#148 [오성준] sprint4
  global.css
  images/banner-bottom.png
  images/banner-top.png
  images/ic-facebook.png
  images/ic-instagram.png
  images/ic-twitter.png
  images/ic-youtube.png
  images/landing-01.png
  images/landing-02.png
  images/landing-03.png
  images/non-visible.svg
  images/visible.svg
  index.html
  js/login.js
  js/signup.js
  login.css
  login.html
  signin.html
  signup.css
  signup.html
  styles.css
  styles/auth.css
  styles/global.css
  styles/index.css
  styles/reset.css
Labels: 매운맛🔥

#154 [고용빈] sprint4-2
  .vscode/settings.json
  js/domElements.js
  js/errorHandlers.js
  js/inputHandlers.js
  js/inputValidators.js
  js/login.js
  js/signup.js
  js/validateLogin.js
  js/validateSignUp.js
  js/validation.js
  signin.html
  signup.html
Labels: 매운맛🔥

#149 [김예준] Sprint5
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/component-ui/PaginationBar.css
  src/component-ui/PaginationBar.js
  src/component-ui/layout/Header.css
  src/component-ui/layout/Header.js
  src/image/hearticon.svg
  src/image/lefticon.svg
  src/image/logo.svg
  src/image/righticon.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/HomePage/HomePage.js
  src/pages/ItemPage/ItemPage.css
  src/pages/ItemPage/ItemPage.js
  src/pages/ItemPage/component/AllItem.js
  src/pages/ItemPage/component/BestItem.js
  src/pages/ItemPage/component/ItemCard.js
  src/reportWebVitals.js
  src/service/Api.js
  src/setupTests.js
  src/style/global.css
Labels: 매운맛🔥

#151 [장아영] sprint5
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/logoImg.png
  src/assets/logoimg.svg
  src/components/MenuTab.jsx
  src/components/bestproducts.jsx
  src/components/header.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/style/bestProducts.css
  src/style/header.css
Labels: 매운맛🔥, 미완성🫠

#169 [이태진] Sprint5
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/icons/ic_arrow_down.svg
  src/assets/icons/ic_heart.svg
  src/assets/icons/ic_search.svg
  src/assets/icons/ic_sort.svg
  src/assets/images/img_logo_chracter_s.png
  src/assets/images/img_logo_s.png
  src/components/BestProductList.js
  src/components/Pagination.js
  src/components/ProductController.js
  src/components/ProductList.js
  src/components/SelectBox.js
  src/components/TopNavigation.js
  src/fonts/Pretendard/Pretendard-Black.ttf
  src/fonts/Pretendard/Pretendard-Bold.ttf
  src/fonts/Pretendard/Pretendard-ExtraBold.ttf
  src/fonts/Pretendard/Pretendard-ExtraLight.ttf
  src/fonts/Pretendard/Pretendard-Light.ttf
  src/fonts/Pretendard/Pretendard-Medium.ttf
  src/fonts/Pretendard/Pretendard-Regular.ttf
  src/fonts/Pretendard/Pretendard-SemiBold.ttf
  src/fonts/Pretendard/Pretendard-Thin.ttf
  src/index.css
  src/index.js
  src/pages/AddItem.js
  src/pages/NotFound.js
  src/pages/UsedMarket.js
  src/styles/AddItem.css
  src/styles/App.css
  src/styles/BestProductList.css
  src/styles/NotFound.css
  src/styles/Pagination.css
  src/styles/ProductController.css
  src/styles/ProductList.css
  src/styles/SelectBox.css
  src/styles/TopNavigation.css
  src/styles/UsedMarket.css
  src/styles/global.css
  src/styles/reset.css
Labels: 매운맛🔥

#168 [석지인] Sprint5
  package-lock.json
  package.json
  public/additem/index.html
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/api.js
  src/components/NavBar.js
  src/components/ProductList.css
  src/components/ProductList.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#150 [홍준기] Sprint5
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/Api.js
  src/App.css
  src/App.js
  src/App.test.js
  src/component/AllProductList.js
  src/component/App.css
  src/component/App.js
  src/component/BestProductList.js
  src/component/Header.css
  src/component/Header.js
  src/component/Library.css
  src/component/ProductItem.js
  src/component/images/icon-heart.png
  src/component/images/topLogo.png
  src/component/mediaQuary.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 미완성🫠

#152 [김당찬] Sprint5
  .eslintrc.cjs
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  reset.css
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/Header.jsx
  src/assets/arrow_down_icon.svg
  src/assets/arrow_left.svg
  src/assets/arrow_right.svg
  src/assets/heart_icon.svg
  src/assets/ic_sort.svg
  src/assets/logo.svg
  src/assets/logo_mobile.svg
  src/assets/react.svg
  src/assets/search_icon.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/main.jsx
  src/pages/AddItem/AddItem.jsx
  src/pages/Community/Community.jsx
  src/pages/Home/Home.jsx
  src/pages/Items/AllProductItem.jsx
  src/pages/Items/AllProductList.jsx
  src/pages/Items/BestProductItem.jsx
  src/pages/Items/BestProductList.jsx
  src/pages/Items/Items.jsx
  src/pages/Items/Pagination.jsx
  src/pages/Items/api.js
  src/pages/Items/items.css
  src/pages/Login/Login.jsx
  src/reportWebVitals.js
  src/setupTests.js
  vite.config.js
Labels: 매운맛🔥

#153 [황병선] Sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/images/icon_dropdown.svg
  src/assets/images/icon_favorite.svg
  src/assets/images/icon_search.svg
  src/assets/images/index.js
  src/assets/images/logo_pandamarket.svg
  src/assets/styles/common.css
  src/assets/styles/reset.css
  src/components/AllItemsSection/AllItemsSection.css
  src/components/AllItemsSection/AllItemsSection.js
  src/components/BestItemSection/BestItemsSection.css
  src/components/BestItemSection/BestItemsSection.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/ItemCard/ItemCard.css
  src/components/ItemCard/ItemCard.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/SecondHandMarket/SecondHandMarket.css
  src/pages/SecondHandMarket/SecondHandMarket.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 미완성🫠

#165 [김가영] Sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/AllItem/AllProductList.js
  src/AllItem/Pagination.js
  src/App.css
  src/App.js
  src/App.test.js
  src/BestItem/BestProductList.js
  src/Items.js
  src/Main.js
  src/ProductItem.css
  src/ProductItem.js
  src/api.js
  src/headers/header.css
  src/headers/header.js
  src/images/arrow.svg
  src/images/heart.svg
  src/images/logo.svg
  src/images/search.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#163 [김도용] Sprint 5
  src/App.js
  src/api.js
  src/assets/images/Img_home_01.png
  src/assets/images/Img_home_02.png
  src/assets/images/Img_home_03.png
  src/assets/images/Img_home_bottom.png
  src/assets/images/Img_home_top.png
  src/assets/images/btn_visibility_off.svg
  src/assets/images/btn_visibility_on.svg
  src/assets/images/ic_facebook.png
  src/assets/images/ic_google.png
  src/assets/images/ic_instagram.png
  src/assets/images/ic_kakao.png
  src/assets/images/ic_twitter.png
  src/assets/images/ic_youtube.png
  src/assets/images/icon_favorite.svg
  src/assets/images/logo.png
  src/assets/images/logo_icon.png
  src/assets/images/logo_icon.svg
  src/assets/images/logo_text_normal.svg
  src/assets/images/logo_text_small.svg
  src/components/Button.css
  src/components/Button.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/ItemCard.css
  src/components/ItemCard.jsx
  src/components/SellList.css
  src/components/SellList.jsx
  src/components/globals.css
  src/index.js
  src/modules/css/button.css
  src/modules/css/commonSign.css
  src/modules/css/globals.css
  src/modules/css/index.css
  src/modules/css/indexDesktop.css
  src/modules/css/indexMobile.css
  src/modules/css/indexTablet.css
  src/modules/css/inputSet.css
  src/modules/css/signIn.css
  src/modules/css/signUp.css
  src/modules/js/commonSign.js
Labels: 매운맛🔥, 미완성🫠

#164 [송효정] sprint5
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/Main.js
  src/assets/css/globals.css
  src/assets/css/reset.css
  src/assets/images/logo.png
  src/components/Layout.jsx
  src/components/layout/Header.jsx
  src/components/layout/Header.module.css
  src/components/ui/Pagination.jsx
  src/components/ui/Pagination.module.css
  src/components/ui/ProductItem.jsx
  src/components/ui/ProductList.jsx
  src/components/ui/ProductList.module.css
  src/hooks/useResize.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AddItemPage.js
  src/pages/IndexPage.js
  src/pages/ItemsPage.js
  src/pages/LoginPage.js
  src/pages/SignupPage.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#159 [박재현] Sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api/api.jsx
  src/assets/img/ic_heart.svg
  src/assets/img/panda-market-logo-mobile.png
  src/assets/img/panda-market-logo.png
  src/components/App.jsx
  src/components/Header/Header.jsx
  src/components/Header/NavigationLink.jsx
  src/components/Items/AddItem.jsx
  src/components/Items/BestProductList.jsx
  src/components/Items/DisplayItems.jsx
  src/components/Items/HandlePageSize.jsx
  src/components/Items/Items.jsx
  src/components/Items/Pagination.jsx
  src/components/Items/ProductList.jsx
  src/components/Items/SearchBar.jsx
  src/components/Items/SearchItems.jsx
  src/index.css
  src/index.js
  src/index.jsx
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/Header.module.css
  src/styles/Items.module.css
  src/styles/NavigationLink.module.css
  src/styles/ProductList.module.css
  src/styles/color.css
  src/styles/fonts.css
  src/styles/main.css
  src/styles/reset.css
Labels: 미완성🫠

#158 [서미영] Sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Main.jsx
  src/api/api.js
  src/assets/images/icons/arrow_left.svg
  src/assets/images/icons/arrow_right.svg
  src/assets/images/icons/ic_heart.svg
  src/assets/images/icons/ic_plus.svg
  src/assets/images/icons/ic_search.svg
  src/assets/images/icons/ic_sort.svg
  src/assets/images/icons/ic_x.svg
  src/assets/images/logo/panda-market-logo.svg
  src/components/AllProductItem.jsx
  src/components/AllProductList.jsx
  src/components/App.js
  src/components/BestProductItem.jsx
  src/components/BestProductList.jsx
  src/components/Layout/Header.css
  src/components/Layout/Header.jsx
  src/components/Pagination.jsx
  src/components/ProductPage.css
  src/components/ProductSearch.jsx
  src/hooks/useDeviceType.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AdditemPage.jsx
  src/pages/FreeBoardPage.jsx
  src/pages/HomePage.jsx
  src/pages/Loginpage.jsx
  src/pages/UsedMarketPage.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/common.css
  src/styles/global.css
  src/utils/Utils.jsx
Labels: 매운맛🔥

#167 [하유리] Sprint5
  package-lock.json
  package.json
  public/index.html
  src/Api.js
  src/App.css
  src/App.js
  src/component/Header.css
  src/component/Header.js
  src/component/Products.css
  src/component/Products.js
  src/component/common.css
  src/font/ROKAF-Sans-Bold.woff
  src/font/ROKAF-Sans-Medium.woff
  src/image/pandaMarketLogo.png
  src/index.js
  src/items.js
Labels: 매운맛🔥, 미완성🫠

#172 [오조환] sprint 4
  .vscode/settings.json
  faq.html
  items.html
  javascript/auth.js
  privacy.html
  signin.html
  signup.html
  styles/auth.css
Labels: 미완성🫠
